// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using najemci.Data;

#nullable disable

namespace najemci.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240918170139_BytIdNajemnik")]
    partial class BytIdNajemnik
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("najemci.Models.Byt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cislo")
                        .HasColumnType("int");

                    b.Property<int>("Kauce")
                        .HasColumnType("int");

                    b.Property<string>("Mistnosti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Najem")
                        .HasColumnType("int");

                    b.Property<int>("NajemSluzby")
                        .HasColumnType("int");

                    b.Property<int>("NemovitostId")
                        .HasColumnType("int");

                    b.Property<string>("Patro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rozloha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sluzby")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NemovitostId");

                    b.ToTable("Byty");
                });

            modelBuilder.Entity("najemci.Models.Najemnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BytId")
                        .HasColumnType("int");

                    b.Property<string>("CisloUctu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DatumNarozeni")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NajemOd")
                        .HasColumnType("datetime2");

                    b.Property<string>("RodneCislo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleNajemnika")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BytId");

                    b.ToTable("Najemnici");
                });

            modelBuilder.Entity("najemci.Models.Nemovitost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nemovitosti");
                });

            modelBuilder.Entity("najemci.Models.Byt", b =>
                {
                    b.HasOne("najemci.Models.Nemovitost", "Nemovitost")
                        .WithMany("Byty")
                        .HasForeignKey("NemovitostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nemovitost");
                });

            modelBuilder.Entity("najemci.Models.Najemnik", b =>
                {
                    b.HasOne("najemci.Models.Byt", "Byt")
                        .WithMany("Najemnici")
                        .HasForeignKey("BytId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Byt");
                });

            modelBuilder.Entity("najemci.Models.Byt", b =>
                {
                    b.Navigation("Najemnici");
                });

            modelBuilder.Entity("najemci.Models.Nemovitost", b =>
                {
                    b.Navigation("Byty");
                });
#pragma warning restore 612, 618
        }
    }
}
